language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq valac uuid-dev libevent-dev libarchive-dev intltool re2c libjansson-dev
 - git clone --depth=50 --branch=release-2-11-3 https://bitbucket.org/tildeslash/libzdb.git deps/libzdb
 - git clone --depth=50 --branch=master git://github.com/haiwen/libsearpc.git deps/libsearpc
 - git clone --depth=50 --branch=master git://github.com/haiwen/ccnet.git deps/ccnet
 - curl -L -o libevhtp.tar.gz https://github.com/ellzey/libevhtp/archive/1.2.9.tar.gz
 - tar -xvf libevhtp.tar.gz -C deps
 - cd deps/libevhtp-1.2.9 && cmake . && make -j8 && sudo make install && cd -
 - cd deps/libzdb && ./bootstrap && ./configure --without-postgresql --without-mysql && make -j8 && sudo make install && cd -
 - cd deps/libsearpc && ./autogen.sh && ./configure
 - cd demo && python ../lib/searpc-codegen.py rpc_table.py && cd -
 - cd tests && python ../lib/searpc-codegen.py rpc_table.py && cd -
 - make -j8 && sudo make install && cd ../..
 - cd deps/ccnet && ./autogen.sh && ./configure --enable-client --enable-server
 - cd lib && python `which searpc-codegen.py` ./rpc_table.py && cd -
 - make -j8 && sudo make install && cd ../..
 - ./autogen.sh
script:
 - cd lib && python `which searpc-codegen.py` ./rpc_table.py && cd -
 - ./configure --disable-fuse --enable-client --enable-server
 - make -j8
notifications:
    email: false
